version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: agendamentopro-rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação da API (AMQP)
      - "15672:15672" # Porta do Painel Web (Dashboard)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest