name: Build, Test and Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-test-deploy:
    runs-on: windows-latest
    
    strategy:
      matrix:
        include:
          - branch: develop
            environment: staging
            api-app-name: 'agendamentopro-api-ricardo-staging'
            web-app-name: 'agendamentopro-web-staging' # (Ajuste se tiver um front de staging)
          - branch: main
            environment: production
            api-app-name: 'agendamentopro-api-ricardo-aydrd0gbcxcacpb8'
            web-app-name: 'agendamentopro-web-prod'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore AgendamentoPro.sln

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Run Tests
      run: dotnet test Tests/Tests.csproj -c Release --no-build --verbosity normal

    # ==========================================
    # ETAPAS DA API
    # ==========================================
    - name: Publish API
      if: success()
      run: dotnet publish API/API.csproj -c Release -o ./publish-api -r win-x86 --self-contained false

    - name: Deploy API to Azure
      if: success() && github.ref == format('refs/heads/{0}', matrix.branch)
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ matrix.api-app-name }}
        publish-profile: ${{ secrets[format('AZURE_PUBLISH_PROFILE_{0}', matrix.environment)] }}
        package: ./publish-api

    # ==========================================
    # ETAPAS DO FRONT-END (BLAZOR)
    # ==========================================
    - name: Publish FrontEnd
      if: success() && github.ref == 'refs/heads/main' # Roda apenas na main para a produção atual
      run: dotnet publish AgendamentoPro.FrontEnd/AgendamentoPro.FrontEnd/AgendamentoPro.FrontEnd.csproj -c Release -o ./publish-frontend

    - name: Compress FrontEnd Folder
      if: success() && github.ref == 'refs/heads/main'
      run: tar -a -c -f ./publish-frontend.zip -C ./publish-frontend .

    - name: Deploy FrontEnd to Azure
      if: success() && github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ matrix.web-app-name }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: './publish-frontend.zip'